=== BackupTheBerlios/snap-svn/trunk/Installation/Settings/Resource.types.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!--                                      -->
  <!--                                      -->
  <!--                                      -->
  <!--                                      -->
  <!-- this is the main object of the XML   -->
  <!-- just a collection of resource types  -->
  <!--                                      -->
  <!--                                      -->
  <xs:element name="resource_types" type="resource_types" />

  <!--                              -->
  <!--                              -->
  <!-- define the text type -->
  <!--                              -->
  <!--                              -->
  <xs:complexType name="fields-text">
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="help" type="xs:string" use="required" />
  </xs:complexType>
  <!--                              -->
  <!--                              -->
  <!-- define the external_ref type -->
  <!--                              -->
  <!--                              -->
  <xs:complexType name="fields-external_ref">
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="help" type="xs:string" use="required" />
    <xs:attribute name="mask" type="xs:string" use="required" />
  </xs:complexType>
  <!--                              -->
  <!--                              -->
  <!-- define the internal_ref type -->
  <!--                              -->
  <!--                              -->
  <xs:complexType name="fields-internal_ref">
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="help" type="xs:string" use="required" />
    <xs:attribute name="minOccurs" type="xs:unsignedByte" use="optional" />
    <xs:attribute name="maxOccurs" type="xs:string" use="optional" />
    <xs:attribute name="mask" type="xs:string" use="optional" />
  </xs:complexType>
  <!--                              -->
  <!--                              -->
  <!--                              -->
  <!-- defines the numeric type     -->
  <!--                              -->
  <!--                              -->
  <xs:complexType name="fields-numeric">
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="display_name" type="xs:string" use="required" />
    <xs:attribute name="help" type="xs:string" use="required" />
    <xs:attribute name="Help" type="xs:string" use="optional" />
    <xs:attribute name="default" type="xs:decimal" use="required" />
    <xs:attribute name="min" type="xs:decimal" use="optional" />
    <xs:attribute name="max" type="xs:decimal" use="optional" />
  </xs:complexType>
  <!--                              -->
  <!--                              -->
  <!-- define the enum_element type -->
  <!--                              -->
  <!--                              -->
  <xs:complexType name="fields-enum-element">
    <xs:sequence>
      <!-- allow text fields-->
      <xs:element minOccurs="0" maxOccurs="unbounded" name="text" type="fields-text" />
      <!-- allow internal refs -->
      <xs:element minOccurs="0" maxOccurs="unbounded" name="internal_ref" type="fields-internal_ref" />
      <!-- allow external refs -->
      <xs:element minOccurs="0" maxOccurs="unbounded" name="external_ref" type="fields-external_ref" />
      <!-- allow numeric -->
      <xs:element minOccurs="0" maxOccurs="unbounded" name="numeric" type="fields-numeric" />
      <!-- allow enums -->
      <xs:element minOccurs="0" maxOccurs="unbounded" name="enum" type="fields-enum" />
    </xs:sequence>
    <!-- attributes must be defined -->
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="display_name" type="xs:string" use="required" />
    <xs:attribute name="help" type="xs:string" use="required" />
  </xs:complexType>
  <!--                              -->
  <!--                              -->
  <!-- define the enum type         -->
  <!--                              -->
  <!--                              -->
  <xs:complexType name="fields-enum">
    <xs:sequence>
      <!-- contains one or more enum_elements-->
      <xs:element minOccurs="1" maxOccurs="unbounded" name="enum_element" type="fields-enum-element" />
    </xs:sequence>
    <!-- attributes must be defined -->
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="display_name" type="xs:string" use="required" />
    <xs:attribute name="help" type="xs:string" use="required" />
  </xs:complexType>
  <!--                              -->
  <!--                              -->
  <!-- define the import type       -->
  <!--                              -->
  <!--                              -->
  <xs:complexType name="execute-import">
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>
  <!--                              -->
  <!--                              -->
  <!-- define the path type         -->
  <!--                              -->
  <!--                              -->
  <xs:complexType name="export-path">
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="value" type="xs:string" use="required" />
  </xs:complexType>
  <!--                              -->
  <!--                              -->
  <!-- define the text type         -->
  <!--                              -->
  <!--                              -->
  <xs:complexType name="export-text">
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="value" type="xs:string" use="required" />
  </xs:complexType>
  <!--                              -->
  <!--                              -->
  <!-- define the "and" conditional -->
  <!--                              -->
  <!--                              -->
  <xs:complexType name="and">
    <xs:sequence>
      <xs:element name="and" type="and" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="or" type="or" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="not" type="not" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="equals" type="equals" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <!--                              -->
  <!--                              -->
  <!-- define the "or" conditional  -->
  <!--                              -->
  <!--                              -->
  <xs:complexType name="or">
    <xs:sequence>
      <xs:element name="and" type="and" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="or" type="or" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="not" type="not" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="equals" type="equals" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <!--                              -->
  <!--                              -->
  <!-- define the "not" conditional -->
  <!--                              -->
  <!--                              -->
  <xs:complexType name="not">
    <xs:choice>
      <xs:element name="and" type="and" />
      <xs:element name="or" type="or" />
      <xs:element name="not" type="not" />
      <xs:element name="equals" type="equals" />
    </xs:choice>
  </xs:complexType>
  <!--                                -->
  <!--                                -->
  <!-- defines the equals conditional -->
  <!--                                -->
  <!--                                -->
  <xs:complexType name="equals">
    <xs:attribute name="A" type="xs:string" use="required" />
    <xs:attribute name="B" type="xs:string" use="required" />
  </xs:complexType>
  <!--                              -->
  <!--                              -->
  <!-- defines the export type      -->
  <!--                              -->
  <!--                              -->
  <xs:complexType name="export">
    <xs:sequence>
      <xs:element name="path" type="export-path" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="text" type="export-text" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="export-conditional" type="export-conditional" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
    <!-- must specify the type of export. currently only "params" style export is supported -->
    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="params" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <!--                                    -->
  <!--                                    -->
  <!-- define the conditional for exports -->
  <!--                                    -->
  <!--                                    -->
  <xs:complexType name="export-conditional">
    <xs:sequence>
      <!-- "if" section -->
      <xs:element name="if" type="and" />
      <!-- "then" section -->
      <xs:element name="then">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="path" type="export-path" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="text" type="export-text" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="export-conditional" type="export-conditional" minOccurs="0" maxOccurs="unbounded" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <!-- "else" optional section -->
      <xs:element name="else" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="path" type="export-path" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="text" type="export-text" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="export-conditional" type="export-conditional" minOccurs="0" maxOccurs="unbounded" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <!--                                -->
  <!--                                -->
  <!-- define the general conditional -->
  <!--                                -->
  <!--                                -->
  <xs:complexType name="execute-conditional">
    <xs:sequence>
      <!-- "if" section -->
      <xs:element name="if" type="and" />
      <!-- "then" section -->
      <xs:element name="then">
        <xs:complexType>
          <xs:sequence>
            <!-- allow conditionals -->
            <xs:element name="conditional" type="execute-conditional" minOccurs="0" maxOccurs="unbounded" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <!-- "else" optional section -->
      <xs:element name="else" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <!-- allow conditionals -->
            <xs:element name="conditional" type="execute-conditional" minOccurs="0" maxOccurs="unbounded" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <!--                              -->
  <!--                              -->
  <!-- define the run type          -->
  <!--                              -->
  <!--                              -->
  <xs:complexType name="execute-run">
    <xs:attribute name="bin" type="xs:string" use="required" />
    <xs:attribute name="params" type="xs:string" use="required" />
  </xs:complexType>
  <!--                              -->
  <!--                              -->
  <!-- define the execute type      -->
  <!--                              -->
  <!--                              -->
  <xs:complexType name="execute">
    <xs:sequence>
      <xs:element name="export" type="export" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="run" type="execute-run" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="import" type="execute-import" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="conditional" type="execute-conditional" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="help" type="xs:string" use="required" />
  </xs:complexType>
  <!--                              -->
  <!--                              -->
  <!-- define the resource_tye type -->
  <!--                              -->
  <!--                              -->
  <xs:complexType name="resource_type">
    <xs:sequence>
      <!-- allows all possible fields -->
      <xs:element name="text" type="fields-text" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="internal_ref" type="fields-internal_ref" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="external_ref" type="fields-external_ref" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="numeric" type="fields-numeric" minOccurs="0" maxOccurs="unbounded" />
      <xs:element name="enum" type="fields-enum" minOccurs="0" maxOccurs="unbounded" />
      <!-- allows executions -->
      <xs:element name="execute" type="execute" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="help" type="xs:string" use="required" />
  </xs:complexType>
  <!--                                -->
  <!--                                -->
  <!-- define the resource_types type -->
  <!--                                -->
  <!--                                -->
  <xs:complexType name="resource_types">
    <xs:sequence>
      <xs:element name="resource_type" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>


</xs:schema>

=== BackupTheBerlios/snap-svn/trunk/Installation/Settings/Resources.types.xml
<?xml version="1.0" encoding="utf-8"?>

<resource_types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Resource.types.xsd">

	<resource_type name="Notes" help="Miscellanious notes">
		<text name="Notes" help="Free text that the user can maintain"/>
	</resource_type>

	<resource_type name="Sequence File" help="Fasta sequence file">
		<text name="Notes" help="Free text that the user can maintain"/>
    <external_ref name="File" help="Path to the sequence on local computer"
			mask="Sequence Files (*.seq) | *.seq"/>
		<execute name="View" help="Open the file in notepad">
			<run bin="notepad.exe" params="$File$"/>
		</execute>
	</resource_type>

	<resource_type name="Weight File" help="Weight file">
		<text name="Notes" help="Free text that the user can maintain"/>
		<external_ref name="File" help="Path to the sequence on local computer"
			mask="Weight Files (*.wgt) | *.wgt"/>
		<execute name="View" help="Open the file in notepad">
			<run bin="notepad.exe" params="$File$"/>
		</execute>
	</resource_type>

	<resource_type name="Conf File" help="Conf file">
		<text name="Notes" help="Free text that the user can maintain"/>
		<external_ref name="File" help="Path to the conf file on local computer"
			mask="Conf Files (*.conf) | *.conf"/>
		<execute name="View" help="Open the file in notepad">
			<run bin="notepad.exe" params="$File$"/>
		</execute>
		<execute name="View/Edit in Conf Editor" help="Open the file in Conf Editor">
			<run bin="ConfEditor.exe" params="$File$"/>
		</execute>
	</resource_type>

	<resource_type name="Family" help="">
		<text name="Notes" help="Free text that the user can maintain"/>
		<internal_ref name="Child" help="" minOccurs="0" maxOccurs="unbounded"/>
	</resource_type>

	<resource_type name="Ab-inito motif search" help="Uses the seed searcher program to look for...">
		<internal_ref name="Sequence File" help="" mask="Sequence Files | Sequence File"/>
		<internal_ref name="Weight File" help="" mask="Weight Files | Weight File"/>
		<internal_ref name="Conf File" help="" mask="Conf Files | Conf File"/>
		<execute name="run" help="">
			<run bin="seed.win32.exe"
				params="--Sconf $Conf File.File$ $Sequence File.File$ $Weight File.File$ $ExecutionFolder$/$Name$"/>
			<import name="summary.xml"/>
		</execute>
	</resource_type>

	<resource_type name="SNAP Seeds file" help="">
		<external_ref name="File" help="" mask="SNAP Seeds file (*.seeds) | *.seeds"/>
		<execute name="View/Edit in notepad" help="Open the file in notepad">
			<run bin="notepad.exe" params="$File$"/>
		</execute>
	</resource_type>

	<resource_type name="SNAP Motifs file" help="">
		<external_ref name="File" help="" mask="SNAP Motifs file (*.motifs) | *.motifs"/>
		<execute name="View/Edit in notepad" help="Open the file in notepad">
			<run bin="notepad.exe" params="$File$"/>
		</execute>
	</resource_type>

	<resource_type name="SNAP PSSM file" help="">
		<external_ref name="File" help="" mask="SNAP PSSM file (*.pssm) | *.pssm"/>
		<execute name="View/Edit in notepad" help="Open the file in notepad">
			<run bin="notepad.exe" params="$File$"/>
		</execute>
	</resource_type>

	<resource_type name="SNAP Matrix file" help="">
		<external_ref name="File" help="" mask="SNAP Matrix file (*.matrix) | *.matrix"/>
		<execute name="View/Edit in notepad" help="Open the file in notepad">
			<run bin="notepad.exe" params="$File$"/>
		</execute>
	</resource_type>

	<resource_type name="Compute Target Overlap" help="">
		<internal_ref name="Seeds file" help="" mask="SNAP Seeds file | SNAP Seeds file"/>
		<execute name="run" help="">
			<export type="params" name="params/ComputeTargetOverlap.params">
				<path name="-seedsFile" value="$Seeds file.File$"/>
				<path name="-dataDir" value="$Seeds file.File.Folder$"/>
				<path name="-out" value="$ExecutionFolder$/ComputeTargetOverlap"/>
				<path name="-hgprog" value="$PluginFolder.Unix$/Share/hgPval.pl"/>
				<path name="-redprog" value="$PluginFolder.Unix$/ComputeTargetOverlap/ComputeRedundancy.awk"
				/>
			</export>
			<export type="params" name="params/Bin.params">
				<text name="-awkcom" value="awk -f"/>
				<text name="-prlcom" value="perl -I $PluginFolder.Unix$/Share/site_perl"/>
				<text name="-gnpltcom" value="gnuplot"/>
			</export>
			<run bin="c:\cygwin\bin\perl.exe" params="$PluginFolder.Unix$/ComputeTargetOverlap.pl"/>
		</execute>
	</resource_type>

	<resource_type name="Compute Positional Bias" help="">
		<internal_ref name="Seeds file" help="" mask="SNAP Seeds File | SNAP Seeds file"/>

		<enum name="RelPosition" display_name="Distance function" help="How we search the cats">
			<enum_element name="S_END" display_name="From end of sequence"
				help="Will compute the bias from the end of the sequence"/>

			<enum_element name="S_START" display_name="From start of sequence"
				help="Will compute the bias from the beginning of the sequence">
				<internal_ref name="Reference sequence file" help="" mask="Sequence File | Sequence File"/>
			</enum_element>

			<enum_element name="MINDIST" display_name="Minimize relative distance"
				help="Computes the bias from either the beginning or end of sequence, favoring the minimal distance">
				<internal_ref name="Reference sequence file" help="" mask="Sequence File | Sequence File"/>
			</enum_element>

		</enum>
		<numeric name="MinPosCount" display_name="Minimum number of occurrences in positive group"
			help="Define the minimum number of occurrences in the positive group for the script to create a figure for the distribution"
			default="3" min="0"/>
		<numeric name="MinNegCount" display_name="Minimum number of occurrences in negative group"
			help="Define the minimum number of occurrences in the negative group for the script to create a figure for the distribution"
			min="0" default="0"/>
		<numeric name="Outliers" display_name="Outliers percentage"
			help="Define the percentage of outliers to remove when computing statistics for the positional bias distribution"
			min="0" max="100" default="30"/>
		<execute name="run" help="">
			<export type="params" name="params/ComputePosBias.params">
				<path name="-seedsFile" value="$Seeds file.File$"/>
				<path name="-dataDir" value="$Seeds file.File.Folder$"/>
				<path name="-out" value="$ExecutionFolder$/ComputePosBias"/>
				<text name="-outlr" value="$Outliers$"/>
				<text name="-minNegCount" value="$MinNegCount$"/>
				<text name="-minPosCount" value="$MinPosCount$"/>
				<path name="-baseGnuF" value="$PluginFolder$/ComputePosBias/basicPosBiasPlot.gnu"/>
				<path name="-ksProg" value="$PluginFolder$/Share/KS.pl"/>
				<path name="-histProg"
					value="$PluginFolder$/ComputePosBias/compPosBiasHist.SlidingWindow.awk"/>
				<text name="-relPosition" value="$RelPosition.Selected.Name$"/>
				<conditional>
					<if>
						<not>
							<equals A="$RelPosition.Selected.Name$" B="S_END"/>
						</not>
					</if>
					<then>
						<path name="-seqF" value="$RelPosition.Selected.Reference sequence file.File$"/>
					</then>
				</conditional>
			</export>
			<export type="params" name="params/Bin.params">
				<text name="-awkcom" value="awk -f"/>
				<text name="-prlcom" value="perl -I $PluginFolder.Unix$/Share/site_perl"/>
				<text name="-gnpltcom" value="gnuplot"/>
			</export>
			<run bin="c:\cygwin\bin\perl.exe" params="$PluginFolder.Unix$/ComputePosBias.pl"/>
		</execute>
	</resource_type>


  <!--                          -->
  <!--                          -->
  <!-- Compute relative dist    -->
  <!--                          -->
  <!--                          -->
  <resource_type name="Compute Relative Distance" help="">
    <internal_ref name="Seeds file" help="" mask="SNAP Seeds File | SNAP Seeds file"/>

    <numeric name="MinCount" display_name="Minimum Count"
			help=""
			default="5" min="0"/>
    <numeric name="Outliers" display_name="Outliers"
			help=""
			min="0"  default="40"/>
    
    <execute name="run" help="">
      <export type="params" name="params/ComputeRelDist.params">
        <path name="-seedsFile" value="$Seeds file.File$"/>
        <path name="-dataDir" value="$Seeds file.File.Folder$"/>
        <path name="-out" value="$ExecutionFolder$/ComputeRelDist"/>
        <text name="-outlr" value="$Outliers$"/>
        <text name="-minCount" value="$MinCount$"/>
        <path name="-baseGnuF" value="$PluginFolder$/ComputePosBias/basicPosBiasPlot.gnu"/>
        <path name="-histProg" value="$PluginFolder$/Share/HistSlidingWind.pl" />
        <path name="-seqlogprg" value="$PluginFolder$/Share/makefig.pl" />
      </export>
      <export type="params" name="params/Bin.params">
        <text name="-awkcom" value="awk -f"/>
        <text name="-prlcom" value="perl -I $PluginFolder.Unix$/Share/site_perl"/>
        <text name="-gnpltcom" value="gnuplot"/>
      </export>
      <run bin="c:\cygwin\bin\perl.exe" params="$PluginFolder.Unix$/ComputeRelDist.pl"/>
    </execute>
  </resource_type>

  <resource_type name="Relative Distance tab summary" help="">
    <external_ref name="File" help="" mask="*.rd | *.rd"/>
    <execute name="View in notepad" help ="">
      <run bin ="notepad" params="$File$"/>
    </execute>
  </resource_type>
  
  <resource_type name="Relative Distance Html Summary" help="">
    <external_ref name="File" help="" mask="HTML files (*.htm, *.html) | *.html, *.htm"/>
    <execute name="View in explorer 7" help ="">
      <run bin ="C:\Program Files\Internet Explorer\iexplore.exe" params="$File$"/>
    </execute>
    <execute name="View in explorer" help ="">
      <run bin ="iexplore.exe" params="$File$"/>
    </execute>
  </resource_type>  
  
</resource_types>
